### ISSUE TITLE
My files are half the size they should be!

### ISSUE THREAD

**Issue by Danthehedgefox** [dubasdey/File-Splitter#12]
I'm not sure if I did something wrong or what, but I tried splitting a 4 gig file apart and the files that resulted only added up to 2 gig. I'm still trying to puzzle out if this is user error but meantime I appreciate some help, thank you.

**Comment by dubasdey** [comment]
Hi @Danthehedgefox, 

Are you using it from command line or from the Graphical interface? If it is from command line please detail the commands used.

Also, you know the format type of the destination drive? 
If the drive is detected as FAT16 the maximum possible file size is 2GB.

**Comment by Danthehedgefox** [comment]
The interface, and I'm using an ntfs drive.

**Comment by Fire-Brand** [comment]
I'm having the same issue, splitting a 900Mb file results in 90 files - 45 of them are 10Mb, and 45 are 100kb(!)

If helps in any way - they come in pairs: 
file_01 = 100 kb
file_02 = 10 MB
file_03 = 100 kb
file_04 = 10 MB 
etc....

**Comment by dubasdey** [comment]
Tested in last master branch with test.bat script added to the solution.

Tested Big file (10 Gb) splitted by size to 100Mb files. Number of files and size OK
Tested 900MB file in 10 MB files. Number of files and size OK

**Comment by dubasdey** [comment]
Fixed in version 1.4.0 Beta 7
