### ISSUE TITLE
megabyte selector not (yet) working in the UI

### ISSUE THREAD

**Issue by pljanson** [dubasdey/File-Splitter#14]
Shows a Incorrect enum.

Solution: 
Update in comboboxitem.cs:
Change from 
        public SplitUnitComboboxItem(String text, SplitUnit key) {
            this.Text = text;
            this.Value = Value; <<<<<<<
        }
to 
    public SplitUnitComboboxItem(String text, SplitUnit key) {
            this.Text = text;
            this.Value = key; <<<<<<  change "value" in "key"!
    }

The project is very new C# 6.0, so I had to change it back to be compatible with my dotnet 4.5 to compile and find the bug. {chnage/Remove writeline($ constructions and some initialization}.

**Comment by dubasdey** [comment]
GUI Dropdown fixed in 1.4.0-b6
