### ISSUE TITLE
-f and -fd Parameter

### ISSUE THREAD

**Issue by Nintendragon** [dubasdey/File-Splitter#15]
Hey!
I really like this project.
Tho, one thing bothers me...
The compiled version on source forge has no Idea of the -f and -fd switches
How this come? they are clearly written in the doc...
I really miss these functions...

**Comment by dubasdey** [comment]
Hi the integration between SourceForge and Github is not updating the project releases. The Sourceforge last version is 1.3.0 and in the github releases the last version is 1.4.0-b6

**Comment by dubasdey** [comment]
Uploaded 1.4.0-b6 zip to SourceForge and relink Github integration.
