### ISSUE TITLE
Puts garbage characters into split files

### ISSUE THREAD

**Issue by Larry8811** [dubasdey/File-Splitter#17]
I needed to split a text file into individual files of 1 line each, so I tried your product. Here's my simple test:

A text file named 4_lines.txt  containing ...
line 1
line 2 
line 3
line 4

Ran fsplit -split 1 l 4_lines.txt -lf result.txt

Here are the contents of 4_lines_1(0).txt through 4_lines_5(0).txt ...

∩╗┐line 1
∩╗┐line 2
∩╗┐line 3
∩╗┐line 4
∩╗┐

Also, notice the additional and unwanted file 4_lines_5(0).txt 
Why was this 5th split file created?

Update 2017Mar07 -- I have been able to continue with my project by using the Gnu utility app "sed" to delete all ASCII characters >= 128 from the split files. But, I wish that you will fix this bug.

Coding to do this for each split file name passed as a quoted parameter %1

@ set p1=%~1
@ set  sed_path="%DataDrive%\program files\gnu\gnuwin32_sed\bin"
@ %sed_path%\sed.exe -i "s/[\d128-\d255]//g" "%TEMP%\fsplit\%p1%" 1>NUL

(There should be a \ preceding the %p1% but this editor has deleted it.)

**Comment by Nintendragon** [comment]
Will this bug be fixed any time soon?

**Comment by dubasdey** [comment]
I'm performing tests with UTF-8 and ISO-8859-1 format files using line split without problem. 

The character is related with the UTF-8 BOM Header. In Unicode editors normaly is hidden but some editors could see it and is not desireable for the batch proceses.

I'm study if is better to create the UTF-8 Files without the BOM header or add an option in the tool to selected the destination encoding.


Sorry, if the fixes and updates delays too time. I update the tool when i have free time and a laptop with VS.

**Comment by dubasdey** [comment]
Added to release **Version 1.4.0 Beta 8**. Testing
