### ISSUE TITLE
Need destination folder selector

### ISSUE THREAD

**Issue by guyrleech** [dubasdey/File-Splitter#18]
Great but it filled up my system drive when I was splitting a file on an external hard drive as I assumed it would put the split parts in the same folder as the source but it put it in the working directory of the splitter process.

Workaround is to cd to the destination folder in cmd/PoSH and then run the tool from there but would be nicer if it had a destination folder selector or at least told you in the UI where it is going to create the split files.

**Comment by dubasdey** [comment]
Working on it

**Comment by guyrleech** [comment]
Thank you

**Comment by dubasdey** [comment]
Path of source file is added as defaut if folder is not specified in console mode or if the tool is running in GUI mode

**Comment by dubasdey** [comment]
Fixed in version 1.4.0 Beta 7
