### ISSUE TITLE
"No space to split"

### ISSUE THREAD

**Issue by rdhoore108** [dubasdey/File-Splitter#22]
When I run fSplit on a file in a folder that is a SymLink to a folder on another drive (so where the contents of that folder is physically on another drive), it tells me that there is not enough space even when there is plenty of space. 

I checked your code, and saw that in FileSplitWorker.cs you are using DriveInfo to get the free space of the drive that is at the root of the current path. In old times, that would have been fine, but nowadays this is not necessarily the drive where the file is actually located.

I'm not sure what is the best way to do this, though... One solution would probably be to use GetDiskFreeSpaceEx() and supply the directory where the input file resides, as explained in https://stackoverflow.com/questions/14465187/get-available-disk-free-space-for-a-given-path-on-windows .

But I see that you are also checking other characteristics of the drive (like FAT limitations), which again should be corrected to use the drive where the file actually really is located on. So the best approach in this case would be to first find out which drive the file really is located on, and only then check the space and limitations of that drive.

However, all this seems really hard in c#. One needs to again use external functions, and more than one it seems. 

Anyway, at least one should be aware of this issue, even if it's too much trouble to fix.

**Comment by dubasdey** [comment]
Thinking about best approach.

Options:
1.- Disable drive format check and use GetDiskFreeSpaceEx
2.- Like 1 but only if the path is not local (required to review if is possible to check path localization)
3.- Add a flag to disable the space checking
