### ISSUE TITLE
but how can i install this after i download ? for GUI mode or i cant even find fsplit utility in that folder

### ISSUE THREAD

**Issue by prashi89** [dubasdey/File-Splitter#24]

**Comment by dubasdey** [comment]
Dowload from [Relases](https://github.com/dubasdey/File-Splitter/releases) the zip named " FileSplitter.zip" of the lastest version.
The file contains the complete package of File splitter. 
Execute "fSplit.exe"  without parameters in your windows to execute the GUI.
Execute "FSplit" from a command line console with parameters to use the Command line process

**Comment by dubasdey** [comment]
Important! To execute the tool is required to have installed .NET Framework 3.5 or newer.

**Comment by hardy2defy** [comment]
thank you very much, couldnt find the exe by downloading the rep
