### ISSUE TITLE
Run on multiple cores

### ISSUE THREAD

**Issue by christianbaumann** [dubasdey/File-Splitter#25]
Hi,

would be nice to be able to run the tool distributed on multiple cores, would speed up things significantly.
What do you think?

Best,
Christian

**Comment by dubasdey** [comment]
That's A good idea for any tool that use the CPU intensively, but not for this tool. This tool have the I/O problem with the disk access. Fastest disk is fastest tool work. Having more parallel CPU processes in one or more computers only makes the code more complicated and do not offer a really relevant beneficts. Also if the processes are in different computers the time to move the data across the network makes the tool really slower.
