### ISSUE TITLE
Usage Help

### ISSUE THREAD

**Issue by dturner1003** [dubasdey/File-Splitter#5]
Hi!
I'm pretty sure this is a user error but I can't figure it out. Forgive me if it is something simple.

I have a 28 kb binary file that I would like broken into 7 parts. I run the command line: "fsplit -split 4 kb c:\myfiles\foo.bin". The output I get is two parts, one with a 4 kb file (as expected) and one file that is 24 kb. How do I get the file to be split into seven 4 kb files?  I ran this with the GUI and get the same results. Thanks!

**Comment by dubasdey** [comment]
Thanks for your comments. I'm inspecting the problem to solve it.

**Comment by dubasdey** [comment]
Test case added to source code. Tested with last version without errors. Pending new release

**Comment by dubasdey** [comment]
Fixed in version 1.4.0 Beta 7
