### ISSUE TITLE
Default padding in file names too long

### ISSUE THREAD

**Issue by fabiankessler** [dubasdey/File-Splitter#6]
Example: my 800MB input file named
myfile_2016-08-04_16-36-50.txt

split into 50MB files generates file names in this form:
myfile__2016-08-04_16-36-50_00000000000000001(00000000000000017).txt

The file splitter program pre-computes how many files there will be, 17 in this case. So it knows it only needs 2 digits. I would prefer a default output file name in one of these forms.

myfile__2016-08-04_16-36-50_1(17).txt
myfile__2016-08-04_16-36-50_01(17).txt

I understand this may be configurable, but I'm not going to complicate things, I just take the default.

**Comment by dubasdey** [comment]
The default pattern could be changed to uses a calculated number or zeroes near the maximun length of the possible number of parts  (length + 1)

**Comment by NKCSS** [comment]
I fixed this in https://github.com/dubasdey/File-Splitter/pull/10
