### ISSUE TITLE
Splitting by line numbers names all files (0)

### ISSUE THREAD

**Issue by fabiankessler** [dubasdey/File-Splitter#7]
My large file was split into 225 small ones. All of them have this pattern with the (0):

mycutfile225(0).txt

This is in contrast to splitting by file size.

**Comment by dubasdey** [comment]
Total number of lines is not calculated at start time.

Calculating the total number of lines at start time could be a high time process. 
We are thinking about how to do it.

**Comment by Larry8811** [comment]
Fixing this shouldn't be a big issue. You already have the logic and coding to count the lines. Just run a Pass 1 without any output to count the lines, then run a Pass 2 normally.

**Comment by dubasdey** [comment]
Yes, it's easy but if testing with a really big file the pass 1 process adds a lot of time at the start with the aplication "preparing" to split. I'm not sure that this option is the better for the time performance.

I think about two posibilities:

1.- In pass 1 count the lines and store the pointer for each split point. In the second pass use the list of pointers to perform the process faster.

2.- Execute the process like now but creating temporal files and rename the files with the real name at the end.

I plan to add this functionality the next time that i will have time to work with this tool. (I make this in my free time, that is not too much )

Thanks to support this application and suggest new functionalities.

**Comment by dubasdey** [comment]
Added using option 1 .

Option 2 is optimal for performance but more complex to implement. Probably added in future

**Comment by dubasdey** [comment]
Fixed in version 1.4.0 Beta 7
